name: trainkun
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  built_collection: ^5.0.0
  built_value: ^8.0.6
  cached_network_image: 2.5.1
  cloud_firestore: ^0.16.0
  flutter_datetime_picker: 1.5.0
  font_awesome_flutter:
  geolocator:
  google_fonts: ^1.1.2
  intl:
  json_serializable: ^3.5.1
  page_transition:
  timeago:
  url_launcher:
  provider: ^5.0.0
  stacked: ^2.2.1
  flutter_spinkit:
  flutter_launcher_icons:


dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.4

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/images/icon.png'
  image_path_ios: 'assets/images/icon.png'
