name: trainkun
description: A new Flutter project.

version: 2.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  http: ^0.13.4
  stacked: ^2.2.1
  flutter_spinkit:
  share: ^2.0.4

  google_fonts: ^2.2.0

  # Firebase SignIn
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  google_sign_in: ^5.2.1
  # Firebase CloudFireStore
  cloud_firestore: ^3.1.5


dev_dependencies:
  build_runner: ^2.1.7

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/images/icon.png'
  image_path_ios: 'assets/images/icon.png'
